- exec: alacritty
  skip_root: true
  path: .config/alacritty
- exec: autorandr
  skip_root: true
  path:
    - .config/autorandr
    - .local/bin/autorandr*
- exec: caddy
  skip_root: true
  path: .config/caddy
- exec: chromium
  skip_root: true
  path: .config/chromium-flags*.conf
- exec: clipman
  skip_root: true
  path: .config/systemd/user/clipman.service
- exec: code
  skip_root: true
  path:
    - .local/bin/code
    - .local/share/applications/visual-studio-code.desktop
- exec: darkman
  skip_root: true
  path:
    - .config/darkman
    - .local/share/dark-mode.d
    - .local/share/light-mode.d
- exec: discord
  skip_root: true
  path:
    - .local/share/applications/discord*
    - .local/bin/discord
- exec: dunst
  skip_root: true
  path:
    - .config/dunst
    - .local/bin/dunst*
    - .config/systemd/user/dunst.service
- exec: feh
  skip_root: true
  path: .config/feh
- exec: firefox
  skip_root: true
  path: .local/share/applications/firefox*
- exec: gammastep
  skip_root: true
  path: .config/gammastep
- exec: glab
  skip_root: true
  path: .config/glab-cli
- exec: google-chrome-stable
  skip_root: true
  path:
    - .config/chrome-flags*.conf
    - .local/share/applications/google-chrome*
    - .local/bin/google-chrome*
- exec: htop
  skip_root: false
  path: .config/htop
- exec: i3
  skip_root: true
  path:
    - .config/i3
    - .local/bin/i3*
    - .local/bin/auto-lock
    - .config/systemd/user/i3-session.target
- exec: kanshi
  skip_root: true
  path:
    - .config/kanshi
    - .config/systemd/user/kanshi.service
    - .local/bin/kanshi*
- exec: kitty
  skip_root: true
  path:
    - .config/kitty
    - .local/bin/self-mon
- exec: nextcloud
  skip_root: true
  path: .config/systemd/user/nextcloud.service
- exec: nvim
  skip_root: false
  path: .config/nvim
- exec: picom
  skip_root: true
  path:
    - .config/picom.conf
    - .config/systemd/user/picom.service
- exec: polybar
  skip_root: true
  path:
    - .config/polybar
    - .local/bin/polybar*
    - .config/systemd/user/polybar.service
- exec: redshift
  skip_root: true
  path:
    - .config/redshift
    - .config/systemd/user/redshift-gtk.service
- exec: rofi
  skip_root: true
  path:
    - .config/rofi
    - .local/bin/rofi*
- exec: slack
  skip_root: true
  path:
    - .local/share/applications/slack*
    - .local/bin/slack
- exec: subl
  skip_root: true
  path: .config/sublime-text
- exec: sublime_text
  skip_root: true
  path: .config/sublime-text-3
- exec: sway
  skip_root: true
  path:
    - .config/sway
    - .config/systemd/user/sway-session.target
    - .local/bin/sway*
- exec: swayidle
  skip_root: true
  path:
    - .config/systemd/user/swayidle.service
    - .local/bin/swayidle
- exec: swayr
  skip_root: true
  path: .config/swayr
- exec: tmuxinator
  skip_root: false
  path: .config/tmuxinator
- exec: waybar
  skip_root: true
  path:
    - .config/waybar
    - .config/systemd/user/waybar.service
    - .config/systemd/user/toggle-input.service
- exec: wlsunset
  skip_root: true
  path: .config/systemd/user/wlsunset.service
- exec: xrandr
  skip_root: true
  path: .local/bin/xorg*
- exec:
    - zed
    - zeditor
  skip_root: true
  path: .config/zed
