#!/usr/bin/bash

if [[ $AUTORANDR_CURRENT_PROFILE = mobile ]]; then
    DPI=192
else
    DPI=120
fi

# Override DPI if required
[[ $(xrdb -query) =~ dpi.*"$DPI" ]] || xrdb -override <<< "Xft.dpi: $DPI"
